version: "1.2"

networks:
  net:
    driver: bridge

services:
  chromadb-server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  loader:
    build: ./script
    depends_on:
      - mongo

  server:
    build: ./server
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - net

  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - net

volumes:
  mongo-data:
  chroma-data:
    driver: local
